/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Rafael
 */
public class frame extends javax.swing.JFrame {

    game theGame;
    ArrayList<Integer> colorsList;
    int click = 0;
    int total_click = 0;
    int canClick = 0;

    /**
     * Creates new form NewJFrame
     */
    public frame() {
  
        initComponents();
  
        theGame = new game(this,red, blue, green, yellow);
              

    }

    public void updateList(ArrayList<Integer> updatedList) throws InterruptedException {
        colorsList = updatedList;
        canClick=1;
        total_click++;
        


        
    }
    
 
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        red = new javax.swing.JPanel();
        blue = new javax.swing.JPanel();
        yellow = new javax.swing.JPanel();
        green = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        red.setBackground(new java.awt.Color(0, 0, 0));
        red.setPreferredSize(new java.awt.Dimension(124, 124));
        red.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                redMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                redMouseExited(evt);
            }
        });

        javax.swing.GroupLayout redLayout = new javax.swing.GroupLayout(red);
        red.setLayout(redLayout);
        redLayout.setHorizontalGroup(
            redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        redLayout.setVerticalGroup(
            redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        blue.setBackground(new java.awt.Color(0, 0, 0));
        blue.setPreferredSize(new java.awt.Dimension(124, 124));
        blue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blueClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blueMouseExited(evt);
            }
        });

        javax.swing.GroupLayout blueLayout = new javax.swing.GroupLayout(blue);
        blue.setLayout(blueLayout);
        blueLayout.setHorizontalGroup(
            blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        blueLayout.setVerticalGroup(
            blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        yellow.setBackground(new java.awt.Color(0, 0, 0));
        yellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yellowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yellowMouseExited(evt);
            }
        });

        javax.swing.GroupLayout yellowLayout = new javax.swing.GroupLayout(yellow);
        yellow.setLayout(yellowLayout);
        yellowLayout.setHorizontalGroup(
            yellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        yellowLayout.setVerticalGroup(
            yellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        green.setBackground(new java.awt.Color(0, 0, 0));
        green.setPreferredSize(new java.awt.Dimension(124, 124));
        green.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                greenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                greenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout greenLayout = new javax.swing.GroupLayout(green);
        green.setLayout(greenLayout);
        greenLayout.setHorizontalGroup(
            greenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        greenLayout.setVerticalGroup(
            greenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        jLabel1.setText("Pontos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setText("Started");
        theGame.start();
        jButton1.setEnabled(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    private void redClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redClicked
       if (canClick==1){
           if(colorsList.get(click) == 0 ){click++;
               if(click == total_click){theGame.unblockThread();click=0;canClick=0;jLabel1.setText("Pontos = " + total_click);}
               }
           else{canClick=0;jButton1.setText("You Lost");}}

    }//GEN-LAST:event_redClicked

    private void yellowClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowClicked
       if (canClick==1){
           if(colorsList.get(click) == 2 ){click++;
               if(click == total_click){theGame.unblockThread();click=0;canClick=0;jLabel1.setText("Pontos = " + total_click);}
               }
           else{canClick=0;jButton1.setText("You Lost");}}
    }//GEN-LAST:event_yellowClicked

    private void blueClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueClicked
       if (canClick==1){
           if(colorsList.get(click) == 3 ){click++;
               if(click == total_click){theGame.unblockThread();click=0;canClick=0;jLabel1.setText("Pontos = " + total_click);}
               }
           else{canClick=0;jButton1.setText("You Lost");}}
    }//GEN-LAST:event_blueClicked

    private void greenClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenClicked
       if (canClick==1){
           if(colorsList.get(click) == 1 ){click++;
               if(click == total_click){theGame.unblockThread();click=0;canClick=0;jLabel1.setText("Pontos = " + total_click);}
               }
           else{canClick=0;jButton1.setText("You Lost");}}
    }//GEN-LAST:event_greenClicked

    
   
    
    
    
    
    private void greenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenMouseEntered
       if(canClick==1 ){ green.setBackground(Color.decode("#00ff00"));                }
    }//GEN-LAST:event_greenMouseEntered

    private void greenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenMouseExited
       if(canClick==1 ){ green.setBackground(Color.decode("#008000"));}
    }//GEN-LAST:event_greenMouseExited

    private void blueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueMouseEntered
        if(canClick==1 ){ blue.setBackground(Color.decode("#0080ff"));} 
    }//GEN-LAST:event_blueMouseEntered

    private void blueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueMouseExited
       if(canClick==1 ){ blue.setBackground(Color.decode("#004080"));}
    }//GEN-LAST:event_blueMouseExited

    private void yellowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowMouseEntered
       if(canClick==1 ){ yellow.setBackground(Color.decode("#ffff00"));} 
    }//GEN-LAST:event_yellowMouseEntered

    private void yellowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowMouseExited
      if(canClick==1 ){ yellow.setBackground(Color.decode("#808000"));}
    }//GEN-LAST:event_yellowMouseExited

    private void redMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redMouseEntered
       if(canClick==1 ){ red.setBackground(Color.decode("#ff0000"));} 
    }//GEN-LAST:event_redMouseEntered

    private void redMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redMouseExited
     if(canClick==1 ){  red.setBackground(Color.decode("#800000"));}
    }//GEN-LAST:event_redMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blue;
    private javax.swing.JPanel green;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel red;
    private javax.swing.JPanel yellow;
    // End of variables declaration//GEN-END:variables
}
